permalink: pretty

plugins:
  - jekyll-remote-theme

remote_theme: cs50/jekyll-theme-cs50

cs50:
  alert: warning dismissible
  description: CS50 at Fulton Science Academy
  image: /static/cat.jpg
  locale: en
  title: CS50 at FSA
  tz: America/New_York